"""baseline (matches backend/prisma/schema.prisma at 20261007120000_profile_field_groups)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-10-09

Autogenerated against the SQLAlchemy models in app/db/models/, then edited to:
  - CREATE TYPE every Postgres enum up front (models declare create_type=False so one
    enum shared across tables, e.g. ResourceVisibility, isn't created twice).
  - DROP TYPE them in downgrade in the reverse order.

Databases that already carry the Prisma-created schema should run
`alembic stamp 0001_baseline` instead of upgrading.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUM_TYPES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("IdentityProvider", ("LOCAL", "GOOGLE")),
    ("EmailTokenType", ("VERIFY_EMAIL", "RESET_PASSWORD")),
    ("FriendshipStatus", ("PENDING", "ACCEPTED")),
    ("ProfileVisibility", ("PUBLIC", "FRIENDS", "PRIVATE")),
    ("TrackProvider", ("DEEZER",)),
    ("ResourceVisibility", ("PUBLIC", "PRIVATE")),
    ("EventLicense", ("EVERYONE", "INVITED", "LOCATION_TIME")),
    ("PlaylistLicense", ("EVERYONE", "INVITED")),
    ("EventStatus", ("DRAFT", "ACTIVE", "ENDED", "CANCELLED")),
    ("EventTrackStatus", ("QUEUED", "PLAYING", "PLAYED")),
    ("ActionLogKind", ("HTTP", "SOCKET", "CLIENT")),
)


def upgrade() -> None:
    for name, values in ENUM_TYPES:
        values_sql = ", ".join(f"'{v}'" for v in values)
        op.execute(f'CREATE TYPE "{name}" AS ENUM ({values_sql})')

    op.create_table(
        "Track",
        sa.Column(
            "provider",
            postgresql.ENUM("DEEZER", name="TrackProvider", create_type=False),
            nullable=False,
        ),
        sa.Column("providerTrackId", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("durationSec", sa.Integer(), nullable=True),
        sa.Column("coverUrl", sa.String(), nullable=True),
        sa.Column("previewUrl", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "providerTrackId", name="Track_provider_providerTrackId_key"
        ),
    )
    op.create_index("Track_artist_idx", "Track", ["artist"], unique=False)
    op.create_index("Track_title_idx", "Track", ["title"], unique=False)
    op.create_table(
        "User",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("passwordHash", sa.String(), nullable=True),
        sa.Column("emailVerifiedAt", sa.DateTime(), nullable=True),
        sa.Column("displayName", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("User_email_idx", "User", ["email"], unique=False)
    op.create_table(
        "ActionLog",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("userId", sa.String(), nullable=True),
        sa.Column(
            "kind",
            postgresql.ENUM("HTTP", "SOCKET", "CLIENT", name="ActionLogKind", create_type=False),
            nullable=False,
        ),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("route", sa.String(), nullable=True),
        sa.Column("statusCode", sa.Integer(), nullable=True),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("device", sa.String(), nullable=False),
        sa.Column("appVersion", sa.String(), nullable=False),
        sa.Column("requestId", sa.String(), nullable=True),
        sa.Column("durationMs", sa.Integer(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ActionLog_createdAt_idx", "ActionLog", ["createdAt"], unique=False)
    op.create_index(
        "ActionLog_kind_createdAt_idx", "ActionLog", ["kind", "createdAt"], unique=False
    )
    op.create_index("ActionLog_route_idx", "ActionLog", ["route"], unique=False)
    op.create_index(
        "ActionLog_userId_createdAt_idx", "ActionLog", ["userId", "createdAt"], unique=False
    )
    op.create_table(
        "EmailToken",
        sa.Column(
            "type",
            postgresql.ENUM(
                "VERIFY_EMAIL", "RESET_PASSWORD", name="EmailTokenType", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("tokenHash", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("expiresAt", sa.DateTime(), nullable=False),
        sa.Column("usedAt", sa.DateTime(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tokenHash"),
    )
    op.create_index("EmailToken_expiresAt_idx", "EmailToken", ["expiresAt"], unique=False)
    op.create_index("EmailToken_userId_type_idx", "EmailToken", ["userId", "type"], unique=False)
    op.create_table(
        "Event",
        sa.Column("ownerId", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "visibility",
            postgresql.ENUM("PUBLIC", "PRIVATE", name="ResourceVisibility", create_type=False),
            server_default="PUBLIC",
            nullable=False,
        ),
        sa.Column(
            "license",
            postgresql.ENUM(
                "EVERYONE", "INVITED", "LOCATION_TIME", name="EventLicense", create_type=False
            ),
            server_default="EVERYONE",
            nullable=False,
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("radiusMeters", sa.Integer(), nullable=True),
        sa.Column("startsAt", sa.DateTime(), nullable=True),
        sa.Column("endsAt", sa.DateTime(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT", "ACTIVE", "ENDED", "CANCELLED", name="EventStatus", create_type=False
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nowPlayingEventTrackId", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["nowPlayingEventTrackId"],
            ["EventTrack.id"],
            name="Event_nowPlayingEventTrackId_fkey",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["ownerId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nowPlayingEventTrackId"),
    )
    op.create_index("Event_ownerId_idx", "Event", ["ownerId"], unique=False)
    op.create_index("Event_startsAt_endsAt_idx", "Event", ["startsAt", "endsAt"], unique=False)
    op.create_index("Event_visibility_status_idx", "Event", ["visibility", "status"], unique=False)
    op.create_table(
        "Friendship",
        sa.Column("requesterId", sa.String(), nullable=False),
        sa.Column("addresseeId", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "ACCEPTED", name="FriendshipStatus", create_type=False),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["addresseeId"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requesterId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "requesterId", "addresseeId", name="Friendship_requesterId_addresseeId_key"
        ),
    )
    op.create_index(
        "Friendship_addresseeId_status_idx", "Friendship", ["addresseeId", "status"], unique=False
    )
    op.create_index(
        "Friendship_requesterId_status_idx", "Friendship", ["requesterId", "status"], unique=False
    )
    op.create_table(
        "Identity",
        sa.Column(
            "provider",
            postgresql.ENUM("LOCAL", "GOOGLE", name="IdentityProvider", create_type=False),
            nullable=False,
        ),
        sa.Column("providerId", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "providerId", name="Identity_provider_providerId_key"),
        sa.UniqueConstraint("provider", "userId", name="Identity_provider_userId_key"),
    )
    op.create_index("Identity_userId_idx", "Identity", ["userId"], unique=False)
    op.create_table(
        "Playlist",
        sa.Column("ownerId", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "visibility",
            postgresql.ENUM("PUBLIC", "PRIVATE", name="ResourceVisibility", create_type=False),
            server_default="PUBLIC",
            nullable=False,
        ),
        sa.Column(
            "license",
            postgresql.ENUM("EVERYONE", "INVITED", name="PlaylistLicense", create_type=False),
            server_default="EVERYONE",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["ownerId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("Playlist_ownerId_idx", "Playlist", ["ownerId"], unique=False)
    op.create_index("Playlist_visibility_idx", "Playlist", ["visibility"], unique=False)
    op.create_table(
        "Profile",
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("avatarUrl", sa.String(), nullable=True),
        sa.Column("realName", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("birthDate", sa.Date(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column(
            "musicGenres", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False
        ),
        sa.Column("musicTags", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False),
        sa.Column(
            "musicVisibility",
            postgresql.ENUM(
                "PUBLIC", "FRIENDS", "PRIVATE", name="ProfileVisibility", create_type=False
            ),
            server_default="PUBLIC",
            nullable=False,
        ),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("userId"),
    )
    op.create_table(
        "RefreshToken",
        sa.Column("tokenHash", sa.String(), nullable=False),
        sa.Column("familyId", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("expiresAt", sa.DateTime(), nullable=False),
        sa.Column("revokedAt", sa.DateTime(), nullable=True),
        sa.Column("replacedById", sa.String(), nullable=True),
        sa.Column("userAgent", sa.String(), nullable=True),
        sa.Column("device", sa.String(), nullable=True),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["replacedById"], ["RefreshToken.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("replacedById"),
        sa.UniqueConstraint("tokenHash"),
    )
    op.create_index("RefreshToken_expiresAt_idx", "RefreshToken", ["expiresAt"], unique=False)
    op.create_index("RefreshToken_familyId_idx", "RefreshToken", ["familyId"], unique=False)
    op.create_index("RefreshToken_userId_idx", "RefreshToken", ["userId"], unique=False)
    op.create_table(
        "EventInvite",
        sa.Column("eventId", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["eventId"], ["Event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eventId", "userId", name="EventInvite_eventId_userId_key"),
    )
    op.create_index("EventInvite_userId_idx", "EventInvite", ["userId"], unique=False)
    op.create_table(
        "EventTrack",
        sa.Column("eventId", sa.String(), nullable=False),
        sa.Column("trackId", sa.String(), nullable=False),
        sa.Column("suggestedById", sa.String(), nullable=False),
        sa.Column("voteCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "QUEUED", "PLAYING", "PLAYED", name="EventTrackStatus", create_type=False
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("playedAt", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["eventId"], ["Event.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suggestedById"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trackId"], ["Track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eventId", "trackId", name="EventTrack_eventId_trackId_key"),
    )
    op.create_index(
        "EventTrack_eventId_status_voteCount_createdAt_idx",
        "EventTrack",
        ["eventId", "status", sa.literal_column('"voteCount" DESC'), "createdAt"],
        unique=False,
    )
    op.create_index("EventTrack_suggestedById_idx", "EventTrack", ["suggestedById"], unique=False)
    op.create_index("EventTrack_trackId_idx", "EventTrack", ["trackId"], unique=False)
    op.create_table(
        "PlaylistMember",
        sa.Column("playlistId", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("canEdit", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["playlistId"], ["Playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlistId", "userId", name="PlaylistMember_playlistId_userId_key"),
    )
    op.create_index("PlaylistMember_userId_idx", "PlaylistMember", ["userId"], unique=False)
    op.create_table(
        "PlaylistTrack",
        sa.Column("playlistId", sa.String(), nullable=False),
        sa.Column("trackId", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("addedById", sa.String(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["addedById"], ["User.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["playlistId"], ["Playlist.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trackId"], ["Track.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playlistId", "trackId", name="PlaylistTrack_playlistId_trackId_key"),
    )
    op.create_index("PlaylistTrack_addedById_idx", "PlaylistTrack", ["addedById"], unique=False)
    op.create_index(
        "PlaylistTrack_playlistId_position_idx",
        "PlaylistTrack",
        ["playlistId", "position"],
        unique=False,
    )
    op.create_index("PlaylistTrack_trackId_idx", "PlaylistTrack", ["trackId"], unique=False)
    op.create_table(
        "Vote",
        sa.Column("eventTrackId", sa.String(), nullable=False),
        sa.Column("userId", sa.String(), nullable=False),
        sa.Column("createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["eventTrackId"], ["EventTrack.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["userId"], ["User.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eventTrackId", "userId", name="Vote_eventTrackId_userId_key"),
    )
    op.create_index("Vote_userId_idx", "Vote", ["userId"], unique=False)


def downgrade() -> None:
    op.drop_index("Vote_userId_idx", table_name="Vote")
    op.drop_table("Vote")
    op.drop_index("PlaylistTrack_trackId_idx", table_name="PlaylistTrack")
    op.drop_index("PlaylistTrack_playlistId_position_idx", table_name="PlaylistTrack")
    op.drop_index("PlaylistTrack_addedById_idx", table_name="PlaylistTrack")
    op.drop_table("PlaylistTrack")
    op.drop_index("PlaylistMember_userId_idx", table_name="PlaylistMember")
    op.drop_table("PlaylistMember")
    op.drop_index("EventTrack_trackId_idx", table_name="EventTrack")
    op.drop_index("EventTrack_suggestedById_idx", table_name="EventTrack")
    op.drop_index("EventTrack_eventId_status_voteCount_createdAt_idx", table_name="EventTrack")
    op.drop_table("EventTrack")
    op.drop_index("EventInvite_userId_idx", table_name="EventInvite")
    op.drop_table("EventInvite")
    op.drop_index("RefreshToken_userId_idx", table_name="RefreshToken")
    op.drop_index("RefreshToken_familyId_idx", table_name="RefreshToken")
    op.drop_index("RefreshToken_expiresAt_idx", table_name="RefreshToken")
    op.drop_table("RefreshToken")
    op.drop_table("Profile")
    op.drop_index("Playlist_visibility_idx", table_name="Playlist")
    op.drop_index("Playlist_ownerId_idx", table_name="Playlist")
    op.drop_table("Playlist")
    op.drop_index("Identity_userId_idx", table_name="Identity")
    op.drop_table("Identity")
    op.drop_index("Friendship_requesterId_status_idx", table_name="Friendship")
    op.drop_index("Friendship_addresseeId_status_idx", table_name="Friendship")
    op.drop_table("Friendship")
    op.drop_index("Event_visibility_status_idx", table_name="Event")
    op.drop_index("Event_startsAt_endsAt_idx", table_name="Event")
    op.drop_index("Event_ownerId_idx", table_name="Event")
    op.drop_table("Event")
    op.drop_index("EmailToken_userId_type_idx", table_name="EmailToken")
    op.drop_index("EmailToken_expiresAt_idx", table_name="EmailToken")
    op.drop_table("EmailToken")
    op.drop_index("ActionLog_userId_createdAt_idx", table_name="ActionLog")
    op.drop_index("ActionLog_route_idx", table_name="ActionLog")
    op.drop_index("ActionLog_kind_createdAt_idx", table_name="ActionLog")
    op.drop_index("ActionLog_createdAt_idx", table_name="ActionLog")
    op.drop_table("ActionLog")
    op.drop_index("User_email_idx", table_name="User")
    op.drop_table("User")
    op.drop_index("Track_title_idx", table_name="Track")
    op.drop_index("Track_artist_idx", table_name="Track")
    op.drop_table("Track")

    for name, _ in reversed(ENUM_TYPES):
        op.execute(f'DROP TYPE "{name}"')
